CREATE TABLE [dbo].[VeteranScreenings] (
  [Id] [int] IDENTITY,
  [VeteranName] [nvarchar](250) NOT NULL,
  [UserId] [nvarchar](450) NOT NULL,
  [CreatedDate] [datetime2] NULL DEFAULT (getutcdate()),
  [LastModified] [datetime2] NULL,
  [HasPcpSignature] [bit] NULL,
  [MedicalConcerns] [bit] NULL,
  [HelpWithInsulin] [bit] NULL,
  [UseOxygen] [bit] NULL,
  [RequiresAssistiveDevice] [bit] NULL,
  [AssistiveDeviceType] [int] NULL,
  [HasMobilityLimitations] [bit] NULL,
  [FluidPills] [bit] NULL,
  [UseInsulin] [bit] NULL,
  [HasMedicalAlerts] [bit] NULL,
  [HasMobilityAlerts] [bit] NULL,
  [HasSpecialAlerts] [bit] NULL,
  [Notes] [nvarchar](500) NOT NULL,
  [ConcernsFlying] [bit] NULL,
  [ConcernsWalkingStairsBus] [bit] NULL,
  [HowMuchOxygen] [nvarchar](500) NOT NULL,
  [MedicalConcernsDetails] [nvarchar](500) NOT NULL,
  [SoundOffNumber] [nvarchar](50) NOT NULL DEFAULT (N''),
  [GuardianName] [nvarchar](250) NOT NULL DEFAULT (N''),
  [GuardianPhone] [nvarchar](12) NOT NULL DEFAULT (N''),
  [LiftRequired] [nvarchar](500) NULL,
  [MobilityAlertsDetails] [nvarchar](500) NOT NULL DEFAULT (N''),
  [SpecialAlertsDetails] [nvarchar](500) NOT NULL DEFAULT (N''),
  CONSTRAINT [PK_VeteranScreenings] PRIMARY KEY CLUSTERED ([Id])
)
GO